name: Check comments follow conventional commit
on: [push, pull_request]

jobs:
  check_conventional_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled so we can bump on previous tags
          fetch-tags: true # This should negate the need for fetch-depth 0 but it seems both are required

      - name: Check for conventional commit
        uses: cocogitto/cocogitto-action@v3.9
        with:
          check-latest-tag-only: true
